spring:
  application.name: swiyu-test-wallet
  jackson.default-property-inclusion: NON_NULL

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

application:
  issuer:
    base-image: "ghcr.io/swiyu-admin-ch/swiyu-issuer"
    image-tag: "${ISSUER_IMAGE_TAG:latest}"
  verifier:
    base-image: "ghcr.io/swiyu-admin-ch/swiyu-verifier"
    image-tag: "${VERIFIER_IMAGE_TAG:latest}"
