spring:
  application.name: swiyu-test-wallet
  jackson.default-property-inclusion: NON_NULL

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

regression:
  issuer:
    previous:
      version: "${REGRESSION_ISSUER_PREVIOUS_VERSION:}"
      variant: "${REGRESSION_ISSUER_PREVIOUS_VARIANT:DEFAULT}"
      metadata: "${REGRESSION_ISSUER_PREVIOUS_METADATA:classpath:issuer/metadata.json}"
    candidate:
      version: "${REGRESSION_ISSUER_CANDIDATE_VERSION:}"
      variant: "${REGRESSION_ISSUER_CANDIDATE_VARIANT:DEFAULT}"
      metadata: "${REGRESSION_ISSUER_CANDIDATE_METADATA:classpath:issuer/metadata.json}"
  verifier:
    previous:
      version: "${REGRESSION_VERIFIER_PREVIOUS_VERSION:}"
      variant: "${REGRESSION_VERIFIER_PREVIOUS_VARIANT:DEFAULT}"
      metadata: "${REGRESSION_VERIFIER_PREVIOUS_METADATA:classpath:verifier/metadata.json}"
    candidate:
      version: "${REGRESSION_VERIFIER_CANDIDATE_VERSION:}"
      variant: "${REGRESSION_VERIFIER_CANDIDATE_VARIANT:DEFAULT}"
      metadata: "${REGRESSION_VERIFIER_CANDIDATE_METADATA:classpath:verifier/metadata.json}"

application:
  issuer:
    base-image: "${ISSUER_IMAGE_NAME:ghcr.io/swiyu-admin-ch/swiyu-issuer}"
    image-tag: "${ISSUER_IMAGE_TAG:dev}"
  verifier:
    base-image: "${VERIFIER_IMAGE_NAME:ghcr.io/swiyu-admin-ch/swiyu-verifier}"
    image-tag: "${VERIFIER_IMAGE_TAG:dev}"
  container-logs:
    issuer: "${ISSUER_CONTAINER_LOGS:true}"
    verifier: "${VERIFIER_CONTAINER_LOGS:true}"
    db: "${DB_CONTAINER_LOGS:false}"
    mock-server: "${MOCKSERVER_CONTAINER_LOGS:false}"
    soft-hsm: "${SOFTHSM_CONTAINER_LOGS:false}"
  trace: "${TRACE_TEST_REQUESTS:false}"
