spring:
  application.name: swiyu-test-wallet
  jackson.default-property-inclusion: NON_NULL

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

application:
  issuer:
    base-image: "${ISSUER_IMAGE_NAME:ghcr.io/swiyu-admin-ch/swiyu-issuer}"
    image-tag: "${ISSUER_IMAGE_TAG:dev}"
  verifier:
    base-image: "${VERIFIER_IMAGE_NAME:ghcr.io/swiyu-admin-ch/swiyu-verifier}"
    image-tag: "${VERIFIER_IMAGE_TAG:dev}"
  trace: "${TRACE_TEST_REQUESTS:false}"